import { Complaint, ComplaintStatus, Severity, User, UserRole } from './types';

export const APP_NAME = 'RASHTRA';

export const COLORS = {
  primary: '#0A3D62',
  secondary: '#1DD1A1',
  alert: '#EE5253',
  warning: '#FBC531',
  white: '#FFFFFF',
  dark: '#121212'
};

export const TRANSLATIONS = {
  en: {
    // Nav
    home: "Home",
    report: "Report Damage",
    status: "Status Track",
    settings: "Settings",
    about: "About",
    logout: "Logout",
    // Settings
    interfacePreferences: "Interface Preferences",
    language: "Language",
    languageDesc: "Choose your preferred language",
    notifications: "System Notifications",
    notificationsDesc: "Receive critical alerts",
    darkMode: "Dark Mode",
    darkModeDesc: "Easier on the eyes",
    support: "Support",
    helpCenter: "Help Center",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    aboutRashtra: "About Rashtra",
    systemConfig: "System Configuration",
    systemDocumentation: "System Documentation",
    // UserHome
    communityFeed: "Community Feed",
    feedSubtitle: "Real-time updates from your neighborhood",
    noReports: "No Reports Yet",
    startReporting: "Start Reporting",
    startReportingDesc: "Be the first to report road damage. Your contribution directly improves our city's infrastructure.",
    // Report
    reportPageTitle: "Report Damage",
    location: "Location",
    details: "Details",
    review: "Review",
    takePhoto: "Take Photo",
    uploadGallery: "Upload from Gallery",
    describeIssue: "Describe the Issue",
    startAnalysis: "Start AI Analysis",
    gpsDetected: "GPS Location Detected",
    pickOnMap: "Pick on Map",
    useGps: "Use Current GPS",
    confirmLocation: "Confirm Location",
    evidenceRequired: "Evidence Required",
    evidenceDesc: "Upload a clear photo of the road damage for AI verification.",
    analyzing: "Analyzing Surface",
    whereIsIssue: "Where is the issue?",
    locationDesc: "We need the precise location to dispatch the correct engineering team.",
    locationLocked: "Location Locked",
    edit: "Edit",
    retake: "Retake",
    severityAssessment: "Severity Assessment",
    registeredAddress: "Registered Address",
    trackStatus: "Track Complaint Status",
    reportAnother: "Report Another Issue",
    // Status
    myComplaints: "My Complaints",
    delete: "Delete",
    noComplaints: "No complaints reported yet.",
    deleteComplaint: "Delete Complaint",
    deleteLocked: "Deletion Locked",
    deleteLockedDesc: "Cannot delete complaint while it is being processed or repaired.",
    confirmDelete: "Are you sure you want to delete this report? This action cannot be undone.",
    // Details Drawer
    discussion: "Discussion",
    description: "Description",
    aiSeverityScore: "AI Severity Score",
    assignedUnit: "Assigned Unit",
    locationMap: "Location Map",
    // Common
    view: "View",
    cancel: "Cancel",
    submit: "Submit",
    lastUpdated: "Last Updated",
    contactUs: "Contact Us",
    // About Page
    aboutSubtitle: "Smart Civic Infrastructure Reporting & Management System",
    ourMission: "Our Mission",
    missionText: "Rashtra aims to bridge the gap between citizens and municipal authorities. By leveraging Artificial Intelligence and Geolocation technology, we empower every citizen to become a guardian of their city's infrastructure.",
    coreTech: "Core Technology",
    coreTechText: "Built on advanced YOLO Computer Vision models, Rashtra automatically verifies complaints, detects pothole severity, and filters out duplicate or fake reports.",
    howItWorks: "How It Works",
    step1Title: "Report",
    step1Desc: "Capture a photo of the road damage.",
    step2Title: "AI Analysis",
    step2Desc: "System verifies severity & location.",
    step3Title: "Action",
    step3Desc: "Authorities dispatch repair teams.",
    step4Title: "Resolved",
    step4Desc: "Get notified when it's fixed.",
    keyFeatures: "Key Features",
    feat1Title: "Real-time Updates",
    feat1Desc: "Track status changes instantly.",
    feat2Title: "Community Driven",
    feat2Desc: "See reports from your neighborhood.",
    feat3Title: "Data Privacy",
    feat3Desc: "Secure and anonymous reporting options.",
    footerRights: "© 2026 Solapur Municipal Corporation. All Rights Reserved.",
    // Help Center
    helpWelcome: "Welcome to the Rashtra Help Centre",
    helpIntro: "We’re here to help you use the platform effectively and responsibly.",
    gettingStarted: "Getting Started",
    whatIsRashtra: "What is Rashtra?",
    whatIsRashtraDesc: "Rashtra is a civic-technology platform that allows citizens to report potholes, flooding, and road hazards. Reports are analyzed using AI and shared with authorities.",
    reportingIssue: "Reporting an Issue",
    howToReport: "How do I report a road issue?",
    locationWhy: "Why is location required?",
    locationWhyDesc: "Location helps accurately identify where the issue exists so that authorities can take action.",
    falseReports: "False or Rejected Reports",
    whyRejected: "Why was my report rejected?",
    whyRejectedDesc: "Reports may be removed if they are false, misleading, spam, or technically invalid.",
    troubleshooting: "Troubleshooting",
    appNotWorking: "App not working properly?",
    importantNotice: "Important Notice",
    emergencyWarning: "Rashtra is not an emergency service. For emergencies, contact local emergency services immediately.",
    // Privacy Policy
    privacyIntro: "Rashtra respects your privacy and is committed to protecting the personal data of its users.",
    infoCollect: "1. Information We Collect",
    infoCollectDesc: "We collect information only when it is necessary to provide our services, including Personal Information, Location Data, and Media.",
    dataUsage: "2. How We Use Your Information",
    dataUsageDesc: "We use collected data for reporting infrastructure issues, AI verification, and improving app performance. We do NOT sell user data.",
    aiProcessing: "3. AI & Automated Processing",
    aiProcessingDesc: "Rashtra uses AI systems for detecting damage and classifying severity.",
    dataSecurity: "4. Data Storage & Security",
    dataSecurityDesc: "User data is securely stored using cloud infrastructure with industry-standard security measures.",
    userRights: "5. User Rights",
    userRightsDesc: "You have the right to access, correct, or delete your personal data.",
    // Terms of Service
    termsIntro: "By accessing or using Rashtra, you agree to comply with and be bound by these Terms of Service.",
    acceptance: "1. Acceptance of Terms",
    acceptanceDesc: "By using Rashtra, you confirm you have read and understood these terms.",
    eligibility: "2. Eligibility",
    eligibilityDesc: "You must be at least 13 years old and provide accurate information.",
    purpose: "3. Purpose of the Service",
    purposeDesc: "Rashtra is for reporting infrastructure issues. It is NOT an emergency service.",
    prohibited: "4. Prohibited Activities",
    prohibitedDesc: "Do not submit false complaints, upload illegal content, or attempt to hack the platform.",
    falseComplaints: "5. False Complaints & Legal Consequences",
    falseComplaintsDesc: "Submission of fake reports is prohibited and may lead to account suspension or legal action.",
    liability: "6. दायित्व की सीमा",
    liabilityDesc: "राष्ट्र सड़क दुर्घटनाओं या प्राधिकरण की कार्रवाई में देरी के लिए उत्तरदायी नहीं है।"
  },
  mr: {
    home: "मुख्यपृष्ठ",
    report: "तक्रार करा",
    status: "स्थिती पहा",
    settings: "सेटिंग्ज",
    about: "माहिती",
    logout: "बाहेर पडा",
    interfacePreferences: "इंटरफेस प्राधान्ये",
    language: "भाषा",
    languageDesc: "तुमची पसंतीची भाषा निवडा",
    notifications: "सिस्टम सूचना",
    notificationsDesc: "महत्त्वाचे अलर्ट मिळवा",
    darkMode: "डार्क मोड",
    darkModeDesc: "डोळ्यांसाठी आरामदायक",
    support: "मदत आणि आधार",
    helpCenter: "मदत केंद्र",
    privacyPolicy: "गोपनीयता धोरण",
    termsOfService: "सेवा अटी",
    aboutRashtra: "राष्ट्र बद्दल",
    systemConfig: "सिस्टम कॉन्फिगरेशन",
    systemDocumentation: "सिस्टम दस्तऐवजीकरण",
    communityFeed: "सामुदायिक फीड",
    feedSubtitle: "तुमच्या परिसरातील अपडेट्स",
    noReports: "अद्याप कोणतीही तक्रार नाही",
    startReporting: "तक्रार नोंदवा",
    startReportingDesc: "रस्त्याच्या नुकसानीची तक्रार करणारे पहिले व्हा. तुमचे योगदान शहराच्या सुधारणेत मदत करेल.",
    reportPageTitle: "नुकसान कळवा",
    location: "स्थान",
    details: "तपशील",
    review: "पुनरावलोकन",
    takePhoto: "फोटो काढा",
    uploadGallery: "गॅलरीतून निवडा",
    describeIssue: "समस्येचे वर्णन करा",
    startAnalysis: "AI विश्लेषण सुरू करा",
    gpsDetected: "GPS स्थान आढळले",
    pickOnMap: "नकाशावर निवडा",
    useGps: "GPS वापरा",
    confirmLocation: "स्थान निश्चित करा",
    evidenceRequired: "पुरावा आवश्यक",
    evidenceDesc: "AI पडताळणीसाठी रस्त्याच्या नुकसानीचा स्पष्ट फोटो अपलोड करा.",
    analyzing: "पृष्ठभाग विश्लेषण",
    whereIsIssue: "समस्या कुठे आहे?",
    locationDesc: "योग्य टीम पाठवण्यासाठी आम्हाला नेमके स्थान हवे आहे.",
    locationLocked: "स्थान निश्चित केले",
    edit: "संपादित करा",
    retake: "पुन्हा घ्या",
    severityAssessment: "तीव्रता मूल्यांकन",
    registeredAddress: "नोंदणीकृत पत्ता",
    trackStatus: "तक्रार स्थिती पहा",
    reportAnother: "दुसरी समस्या कळवा",
    myComplaints: "माझ्या तक्रारी",
    delete: "हटवा",
    noComplaints: "अद्याप कोणतीही तक्रार नोंदवली नाही.",
    deleteComplaint: "तक्रार हटवा",
    deleteLocked: "हटवणे लॉक केले आहे",
    deleteLockedDesc: "प्रक्रिया सुरू असताना तक्रार हटवता येत नाही.",
    confirmDelete: "तुम्हाला ही तक्रार नक्की हटवायची आहे का? ही कृती परत करता येणार नाही.",
    discussion: "चर्चा",
    description: "वर्णन",
    aiSeverityScore: "AI तीव्रता स्कोअर",
    assignedUnit: "नेमून दिलेला विभाग",
    locationMap: "स्थान नकाशा",
    view: "पहा",
    cancel: "रद्द करा",
    submit: "सबमिट करा",
    lastUpdated: "शेवटचे अपडेट",
    contactUs: "संपर्क करा",
    aboutSubtitle: "स्मार्ट नागरी पायाभूत सुविधा अहवाल आणि व्यवस्थापन प्रणाली",
    ourMission: "आमचे ध्येय",
    missionText: "राष्ट्रचा उद्देश नागरिक आणि महानगरपालिका यांच्यातील दरी कमी करणे आहे. कृत्रिम बुद्धिमत्ता आणि भौगोलिक स्थान तंत्रज्ञानाचा वापर करून, आम्ही प्रत्येक नागरिकाला शहराच्या पायाभूत सुविधांचा रक्षक बनवतो.",
    coreTech: "मुख्य तंत्रज्ञान",
    coreTechText: "प्रगत YOLO कॉम्प्युटर व्हिजन मॉडेल्सवर आधारित, राष्ट्र आपोआप तक्रारींची पडताळणी करते, खड्ड्यांची तीव्रता ओळखते आणि बनावट अहवाल फिल्टर करते.",
    howItWorks: "हे कसे कार्य करते",
    step1Title: "तक्रार",
    step1Desc: "रस्त्याच्या नुकसानीचा फोटो काढा.",
    step2Title: "AI विश्लेषण",
    step2Desc: "प्रणाली तीव्रता आणि स्थान पडताळते.",
    step3Title: "कृती",
    step3Desc: "अधिकारी दुरुस्ती पथके पाठवतात.",
    step4Title: "निराकरण",
    step4Desc: "दुरुस्ती झाल्यावर सूचना मिळवा.",
    keyFeatures: "महत्वाची वैशिष्ट्ये",
    feat1Title: "रिअल-टाइम अपडेट्स",
    feat1Desc: "स्थिती बदलांचा त्वरित मागोवा घ्या.",
    feat2Title: "समाज प्रेरित",
    feat2Desc: "तुमच्या शेजारचे अहवाल पहा.",
    feat3Title: "डेटा गोपनीयता",
    feat3Desc: "सुरक्षित आणि निनावी तक्रार पर्याय.",
    footerRights: "© २०२६ सोलापूर महानगरपालिका. सर्व हक्क राखीव.",
    helpWelcome: "राष्ट्र मदत केंद्रात स्वागत आहे",
    helpIntro: "प्लॅटफॉर्म प्रभावीपणे आणि जबाबदारीने वापरण्यास मदत करण्यासाठी आम्ही येथे आहोत.",
    gettingStarted: "सुरुवात करताना",
    whatIsRashtra: "राष्ट्र म्हणजे काय?",
    whatIsRashtraDesc: "राष्ट्र हे एक नागरी-तंत्रज्ञान व्यासपीठ आहे जे नागरिकांना खड्डे, पूर आणि रस्त्यावरील धोके कळविण्यास सक्षम करते.",
    reportingIssue: "समस्या नोंदवणे",
    howToReport: "मी रस्त्याच्या समस्येची तक्रार कशी करू?",
    locationWhy: "स्थान का आवश्यक आहे?",
    locationWhyDesc: "समस्या कोठे आहे हे अचूकपणे ओळखण्यासाठी स्थानाची मदत होते, जेणेकरून अधिकारी कारवाई करू शकतील.",
    falseReports: "खोटे किंवा नाकारलेले अहवाल",
    whyRejected: "माझा अहवाल का नाकारला गेला?",
    whyRejectedDesc: "जर अहवाल खोटे, दिशाभूल करणारे किंवा तांत्रिकदृष्ट्या अवैध असतील तर ते काढले जाऊ शकतात.",
    troubleshooting: "समस्या निवारण",
    appNotWorking: "अॅप योग्यरित्या काम करत नाही?",
    importantNotice: "महत्वाची सूचना",
    emergencyWarning: "राष्ट्र ही आपत्कालीन सेवा नाही. आपत्कालीन परिस्थितीसाठी, स्थानिक आपत्कालीन सेवांशी संपर्क साधा.",
    privacyIntro: "राष्ट्र तुमच्या गोपनीयतेचा आदर करते आणि वापरकर्त्यांचा वैयक्तिक डेटा सुरक्षित ठेवण्यास वचनबद्ध आहे.",
    infoCollect: "१. आम्ही गोळा करत असलेली माहिती",
    infoCollectDesc: "आम्ही फक्त सेवा देण्यासाठी आवश्यक असलेली माहिती गोळा करतो, ज्यात वैयक्तिक माहिती आणि स्थान डेटा समाविष्ट आहे.",
    dataUsage: "२. आम्ही तुमची माहिती कशी वापरतो",
    dataUsageDesc: "आम्ही डेटाचा वापर पायाभूत सुविधांच्या समस्यांचा अहवाल देण्यासाठी आणि अॅप सुधारण्यासाठी करतो. आम्ही डेटा विकत नाही.",
    aiProcessing: "३. AI आणि स्वयंचलित प्रक्रिया",
    aiProcessingDesc: "राष्ट्र नुकसानीचे निदान आणि तीव्रता वर्गीकरणासाठी AI प्रणाली वापरते.",
    dataSecurity: "४. डेटा साठवण आणि सुरक्षा",
    dataSecurityDesc: "वापरकर्ता डेटा सुरक्षित क्लाउड इन्फ्रास्ट्रक्चरवर साठवला जातो.",
    userRights: "५. वापरकर्ता हक्क",
    userRightsDesc: "तुम्हाला तुमचा वैयक्तिक डेटा पाहण्याचा, दुरुस्त करण्याचा किंवा हटवण्याचा अधिकार आहे.",
    termsIntro: "राष्ट्र वापरून, तुम्ही या सेवा अटींशी बांधील राहण्यास सहमती देता.",
    acceptance: "१. अटींची स्वीकृती",
    acceptanceDesc: "अॅप वापरून, तुम्ही पुष्टी करता की तुम्ही या अटी वाचल्या आणि समजल्या आहेत.",
    eligibility: "२. पात्रता",
    eligibilityDesc: "तुमचे वय किमान १३ वर्षे असावे आणि तुम्ही अचूक माहिती देणे आवश्यक आहे.",
    purpose: "३. सेवेचा उद्देश",
    purposeDesc: "राष्ट्र हे पायाभूत सुविधांच्या समस्या नोंदवण्यासाठी आहे. ही आपत्कालीन सेवा नाही.",
    prohibited: "४. प्रतिबंधित क्रियाकलाप",
    prohibitedDesc: "खोट्या तक्रारी सबमिट करू नका किंवा बेकायदेशीर सामग्री अपलोड करू नका.",
    falseComplaints: "५. खोट्या तक्रारी आणि कायदेशीर परिणाम",
    falseComplaintsDesc: "बनावट अहवाल सादर करणे प्रतिबंधित आहे आणि यामुळे खाते निलंबित किंवा कायदेशीर कारवाई होऊ शकते.",
    liability: "६. जबाबदारीची मर्यादा",
    liabilityDesc: "रस्ते अपघात किंवा अधिकाऱ्यांच्या विलंबासाठी राष्ट्र जबाबदार नाही."
  },
  hi: {
    home: "होम",
    report: "शिकायत करें",
    status: "स्थिति देखें",
    settings: "सेटिंग्स",
    about: "परिचय",
    logout: "लॉग आउट",
    interfacePreferences: "इंटरफेस प्राथमिकताएं",
    language: "भाषा",
    languageDesc: "अपनी पसंदीदा भाषा चुनें",
    notifications: "सिस्टम नोटिफिकेशन",
    notificationsDesc: "महत्वपूर्ण अलर्ट प्राप्त करें",
    darkMode: "डार्क मोड",
    darkModeDesc: "आंखों के लिए आरामदायक",
    support: "सहायता और समर्थन",
    helpCenter: "सहायता केंद्र",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    aboutRashtra: "राष्ट्र के बारे में",
    systemConfig: "सिस्टम कॉन्फ़िगरेशन",
    systemDocumentation: "सिस्टम दस्तावेज़ीकरण",
    communityFeed: "सामुदायिक फीड",
    feedSubtitle: "आपके पड़ोस से अपडेट",
    noReports: "अभी तक कोई रिपोर्ट नहीं",
    startReporting: "रिपोर्टिंग शुरू करें",
    startReportingDesc: "सड़क क्षति की रिपोर्ट करने वाले पहले व्यक्ति बनें। आपका योगदान सीधे हमारे शहर के बुनियादी ढांचे में सुधार करता है।",
    reportPageTitle: "नुकसान की रिपोर्ट करें",
    location: "स्थान",
    details: "विवरण",
    review: "समीक्षा",
    takePhoto: "फोटो लें",
    uploadGallery: "गैलरी से अपलोड करें",
    describeIssue: "समस्या का वर्णन करें",
    startAnalysis: "AI विश्लेषण शुरू करें",
    gpsDetected: "GPS स्थान का पता चला",
    pickOnMap: "मानचित्र पर चुनें",
    useGps: "वर्तमान GPS का उपयोग करें",
    confirmLocation: "स्थान की पुष्टि करें",
    evidenceRequired: "सबूत आवश्यक",
    evidenceDesc: "AI सत्यापन के लिए सड़क क्षति की स्पष्ट फोटो अपलोड करें।",
    analyzing: "सतह विश्लेषण",
    whereIsIssue: "समस्या कहाँ है?",
    locationDesc: "सही टीम भेजने के लिए हमें सटीक स्थान की आवश्यकता है।",
    locationLocked: "स्थान लॉक किया गया",
    edit: "संपादित करें",
    retake: "फिर से लें",
    severityAssessment: "गंभीरता मूल्यांकन",
    registeredAddress: "पंजीकृत पता",
    trackStatus: "शिकायत की स्थिति देखें",
    reportAnother: "एक और समस्या रिपोर्ट करें",
    myComplaints: "मेरी शिकायतें",
    delete: "हटाएं",
    noComplaints: "अभी तक कोई शिकायत दर्ज नहीं की गई है।",
    deleteComplaint: "शिकायत हटाएं",
    deleteLocked: "हटाना लॉक है",
    deleteLockedDesc: "प्रक्रिया या मरम्मत के दौरान शिकायत को हटाया नहीं जा सकता।",
    confirmDelete: "क्या आप वाकई इस रिपोर्ट को हटाना चाहते हैं? यह कार्रवाई पूर्ववत नहीं की जा सकती।",
    discussion: "चर्चा",
    description: "विवरण",
    aiSeverityScore: "AI गंभीरता स्कोर",
    assignedUnit: "आवंटित इकाई",
    locationMap: "स्थान मानचित्र",
    view: "देखें",
    cancel: "रद्द करें",
    submit: "जमा करें",
    lastUpdated: "अंतिम अद्यतन",
    contactUs: "संपर्क करें",
    aboutSubtitle: "स्मार्ट नागरिक अवसंरचना रिपोर्टिंग और प्रबंधन प्रणाली",
    ourMission: "हमारा मिशन",
    missionText: "राष्ट्र का उद्देश्य नागरिकों और नगर निगम के अधिकारियों के बीच की खाई को पाटना है। आर्टिफिशियल इंटेलिजेंस और जियोलोकेशन तकनीक का लाभ उठाकर, हम हर नागरिक को अपने शहर की बुनियादी सुविधाओं का संरक्षक बनाते हैं।",
    coreTech: "मुख्य तकनीक",
    coreTechText: "उन्नत YOLO कंप्यूटर विजन मॉडल पर निर्मित, राष्ट्र स्वचालित रूप से शिकायतों को सत्यापित करता है, गड्ढे की गंभीरता का पता लगाता है, और नकली रिपोर्टों को फ़िल्टर करता है।",
    howItWorks: "यह कैसे काम करता है",
    step1Title: "रिपोर्ट",
    step1Desc: "सड़क क्षति की फोटो लें।",
    step2Title: "AI विश्लेषण",
    step2Desc: "सिस्टम गंभीरता और स्थान की पुष्टि करता है।",
    step3Title: "कार्रवाई",
    step3Desc: "अधिकारी मरम्मत दल भेजते हैं।",
    step4Title: "समाधान",
    step4Desc: "मरम्मत होने पर सूचना प्राप्त करें।",
    keyFeatures: "प्रमुख विशेषताएं",
    feat1Title: "रीयल-टाइम अपडेट",
    feat1Desc: "स्थिति परिवर्तनों को तुरंत ट्रैक करें।",
    feat2Title: "समुदाय संचालित",
    feat2Desc: "अपने पड़ोस से रिपोर्ट देखें।",
    feat3Title: "डेटा गोपनीयता",
    feat3Desc: "सुरक्षित और गुमनाम रिपोर्टिंग विकल्प।",
    footerRights: "© 2026 सोलापुर नगर निगम। सर्वाधिकार सुरक्षित।",
    helpWelcome: "राष्ट्र सहायता केंद्र में आपका स्वागत है",
    helpIntro: "हम मंच का प्रभावी और जिम्मेदारी से उपयोग करने में आपकी सहायता के लिए यहां हैं।",
    gettingStarted: "शुरुआत करना",
    whatIsRashtra: "राष्ट्र क्या है?",
    whatIsRashtraDesc: "राष्ट्र एक नागरिक-तकनीक मंच है जो नागरिकों को गड्ढों, बाढ़ और सड़क के खतरों की रिपोर्ट करने की अनुमति देता है।",
    reportingIssue: "मुद्दा रिपोर्ट करना",
    howToReport: "मैं सड़क की समस्या की रिपोर्ट कैसे करूं?",
    locationWhy: "स्थान की आवश्यकता क्यों है?",
    locationWhyDesc: "स्थान समस्या की सटीक पहचान करने में मदद करता है ताकि अधिकारी कार्रवाई कर सकें।",
    falseReports: "झूठी या खारिज की गई रिपोर्ट",
    whyRejected: "मेरी रिपोर्ट क्यों खारिज की गई?",
    whyRejectedDesc: "यदि रिपोर्ट झूठी, भ्रामक, स्पैम या तकनीकी रूप से अमान्य हैं तो उन्हें हटाया जा सकता है।",
    troubleshooting: "समस्या निवारण",
    appNotWorking: "ऐप ठीक से काम नहीं कर रहा है?",
    importantNotice: "महत्वपूर्ण सूचना",
    emergencyWarning: "राष्ट्र कोई आपातकालीन सेवा नहीं है। आपात स्थिति के लिए, तुरंत स्थानीय आपातकालीन सेवाओं से संपर्क करें।",
    privacyIntro: "राष्ट्र आपकी गोपनीयता का सम्मान करता है और अपने उपयोगकर्ताओं के व्यक्तिगत डेटा की सुरक्षा के लिए प्रतिबद्ध है।",
    infoCollect: "1. जानकारी जो हम एकत्र करते हैं",
    infoCollectDesc: "हम केवल आवश्यक जानकारी एकत्र करते हैं, जिसमें व्यक्तिगत जानकारी और स्थान डेटा शामिल है।",
    dataUsage: "2. हम आपकी जानकारी का उपयोग कैसे करते हैं",
    dataUsageDesc: "हम डेटा का उपयोग बुनियादी ढांचे के मुद्दों की रिपोर्ट करने और ऐप को बेहतर बनाने के लिए करते हैं। हम डेटा नहीं बेचते हैं।",
    aiProcessing: "3. AI और स्वचालित प्रसंस्करण",
    aiProcessingDesc: "राष्ट्र क्षति का पता लगाने और गंभीरता वर्गीकरण के लिए AI सिस्टम का उपयोग करता है।",
    dataSecurity: "4. डेटा भंडारण और सुरक्षा",
    dataSecurityDesc: "उपयोगकर्ता डेटा सुरक्षित क्लाउड इन्फ्रास्ट्रक्चर पर उद्योग-मानक सुरक्षा उपायों के साथ संग्रहीत किया जाता है।",
    userRights: "5. उपयोगकर्ता अधिकार",
    userRightsDesc: "आपको अपने व्यक्तिगत डेटा तक पहुंचने, सुधारने या हटाने का अधिकार है।",
    termsIntro: "राष्ट्र का उपयोग करके, आप इन सेवा की शर्तों का पालन करने के लिए सहमत हैं।",
    acceptance: "1. शर्तों की स्वीकृति",
    acceptanceDesc: "ऐप का उपयोग करके, आप पुष्टि करते हैं कि आपने इन शर्तों को पढ़ा और समझा है।",
    eligibility: "2. पात्रता",
    eligibilityDesc: "आपकी आयु कम से कम 13 वर्ष होनी चाहिए और आपको सटीक जानकारी प्रदान करनी होगी।",
    purpose: "3. सेवा का उद्देश्य",
    purposeDesc: "राष्ट्र बुनियादी ढांचे के मुद्दों की रिपोर्टिंग के लिए है। यह आपातकालीन सेवा नहीं है।",
    prohibited: "4. निषिद्ध गतिविधियां",
    prohibitedDesc: "झूठी शिकायतें प्रस्तुत न करें, अवैध सामग्री अपलोड न करें, या हैक करने का प्रयास न करें।",
    falseComplaints: "5. झूठी शिकायतें और कानूनी परिणाम",
    falseComplaintsDesc: "नकली रिपोर्ट जमा करना प्रतिबंधित है और इससे खाता निलंबन या कानूनी कार्रवाई हो सकती है।",
    liability: "6. दायित्व की सीमा",
    liabilityDesc: "राष्ट्र सड़क दुर्घटनाओं या प्राधिकरण की कार्रवाई में देरी के लिए उत्तरदायी नहीं है।"
  }
};

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Rohan Sharma',
  email: 'rohan@example.com',
  role: UserRole.USER,
  avatarUrl: 'https://picsum.photos/100/100',
  phoneNumber: '+91 98765 43210',
  address: 'Juna Plot, Solapur'
};

export const MOCK_ADMIN: User = {
  id: 'a1',
  name: 'Municipal Admin',
  email: 'admin@solapur-municipal.gov.in',
  role: UserRole.ADMIN,
  avatarUrl: 'https://picsum.photos/101/101',
  phoneNumber: '+91 217 274 0300',
  address: 'SMC Head Office, Solapur'
};

export const MOCK_CONTRACTOR_USER: User = {
  id: 'C-101', // Matches Rajesh Kumar in mockApi
  name: 'Rajesh Kumar',
  email: 'rajesh@buildwell.com',
  role: UserRole.CONTRACTOR,
  avatarUrl: 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?auto=format&fit=crop&q=80&w=200',
  phoneNumber: '+91 98220 12345',
  address: 'BuildWell Office, MIDC'
};

export const INITIAL_COMPLAINTS: Complaint[] = [];